x-veld:
  code:
    description: "Veldified version of xml2standoff. All three parameters can be passed as
      environment variables as defined below. On the functions of each, please see:
      https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#xml2standoff"
    topics: ETL

    inputs:
      - volume: /veld/input/
        environment: in_xml_file
        file_type: xml

    outputs:
      - volume: /veld/output/
        environment: out_txt_file
        file_type: txt
      - volume: /veld/output/
        environment: out_json_file
        file_type: json

    settings:
      - environment: text_elements
        description: "Elements to be selected, separated by comma without whitespace in between. For
          more information, see: 
          https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#xml2standoff"
        env_type: str
        optional: true
      - environment: exclude_elements
        description: "Elements to be excluded, separated by comma without whitespace in between. For
          more information, see: 
          https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#xml2standoff"
        env_type: str
        optional: true
      - environment: keep_linebreaks
        description: "Should linebreaks be kept? If not set to true, linebreaks will be removed automatically within contents. For more information, see: 
          https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#xml2standoff"
        env_type: bool
        default: false
        optional: true

services:
  xml2standoff:
    build: .
    volumes:
      - ./:/veld/code/
    command: ./veld_xml2standoff.sh
    environment:
      in_xml_file: null
      out_txt_file: null
      out_json_file: null
      text_elements: null
      exclude_elements: null
      keep_linebreaks: false

