x-veld:
  code:
    description: ""
    topics: NLP

    inputs:

    outputs:

    settings:

services:
  standoff2xml:
    build: .
    volumes:
      - ./:/veld/code/
    command: ./veld_standoff2xml.sh
    environment:
      in_txt_file: null
      in_json_file: null
      in_ann_json_file: null
      out_ann_xml_file: null
      token_annotation: false
      warn_breaking: null
      keep_between_sentences: false

