x-veld:
  code:
    description: "Veldified version of tag_ud. All three parameters can be passed as 
      environment variables as defined below. On the functions of each, please see: 
      https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#tag_ud"
    topics: NLP

    inputs:
      - volume: /veld/input/
        environment: in_txt_file
        file_type: txt

    outputs:
      - volume: /veld/output/
        environment: out_conllu_file
        file_type:
          - tsv
          - conllu

    settings:
      - environment: model
        description: "The UDPipe model proivded by the REST API at 
          https://lindat.mff.cuni.cz/services/udpipe/ . For available models, see here: 
          https://ufal.mff.cuni.cz/udpipe/2/models . For more information on how to use this tag_ud 
          service, see: https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#tag_ud"
        env_type: str
      - environment: batch
        description: "Number of text lines to be sent in batches to the UDPipe REST API. For 
          more information, see: 
          https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#tag_ud"
        env_type: int
        default: 1000
        optional: true
      - environment: verbose
        description: "Boolean flag to set verbose information or not during execution. For more 
          information, see: https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#tag_ud"
        env_type: bool
        default: false
        optional: true

services:
  tag_ud:
    build: .
    volumes:
      - ./:/veld/code/
    command: ./veld_tag_ud.sh
    environment:
      in_txt_file: null
      out_conllu_file: null
      model: null
      batch: 1000
      verbose: false

