x-veld:
  code:
    description: ""
    topics: NLP

    inputs:

    outputs:

    settings:

services:
  ann2standoff:
    build: .
    volumes:
      - ./:/veld/code/
    command: ./veld_ann2standoff.sh
    environment:
      in_conllu_file: null
      in_txt_file: null
      in_ann2standoff_ini_file: null
      out_json_file: null
      profile_name: DEFAULT

